### ISSUE TITLE
Where are the modules? :)

### ISSUE THREAD

**Issue by teamgroove** [uloga/modulr.css#3]
Hello,
i love the approach - it seems totally interesting to me, and i want to use the modules together with webpack/postcss. 

But - where have the modules gone missing? :)

Would you share the current state of module with me, so i can @import them seperately?

Have fun!

René

**Comment by uloga** [comment]
Hi,
The v1 of the fw is out there just to gather some feedback, still working on the final release.
Doing my best to finish it as soon as possible, working only on the weekends tho. 

Working on CLI at the moment, the idea is to able to: 'npm install modulr' and then:
1. modulr generate --projectname 
2. modulr generate --layout or --component
3. modulr from core import <modulename> 
4. modulr from modules import <modulename>
5. modulr watch 
6. write html including expressive CSS classes:  the parser will parse the html by looking at the classes and then generate custom classes based on those classes you use in your project, after that it'll minify the css.  
That way instead of having a gigantic fw included  in your live project, you'll have access to a gigantic modulr fw but will only use small part of it you may actually need for your project.
